Introduce Cypress E2E Testing
near-examples/guest-book-js pull request #10
Opened 2022-11-25 13:08 UTC by idea404

This PR introduces Cypress E2E Testing

2022-11-25 13:08 UTC, idea404 commented
TODO: implement yaml spec

2022-11-28 15:45 UTC, maxhr requested changes

2022-11-28 15:45 UTC, maxhr commented on .gitignore
> +**/videos
do you need **/videos?

2022-11-28 15:45 UTC, maxhr commented on frontend/cypress.config.js
> +const { defineConfig } = require('cypress')
can we place this in cypres folder? to keep root folder clean

2022-11-28 15:45 UTC, maxhr commented on frontend/tsconfig.json
> +{
why tsconfig in frontend?

2022-11-28 15:45 UTC, maxhr commented on frontend/tsconfig.json
> +  "extends": "../tsconfig.json",
this doesn't exist

2022-11-28 15:47 UTC, idea404 commented on .gitignore
> +**/videos
Cypress makes video backups of runs into this folder

2022-11-29 10:28 UTC, idea404 commented on frontend/cypress/e2e/guest-book.cy.ts
> +// Load string from environment variable
I'd argue snapshot tests belong in the unit tests for the front end. We can add these in another PR that includes tests that test the frontend alone. These tests perform network calls additional to how the frontend works

2022-12-05 17:03 UTC, maxhr approved these changes

2022-12-06 08:33 UTC, merged